[project]
name = "lab-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.7",
    "polars>=1.34.0",
    "ruff>=0.14.2",
]
